---
abstract: 'American, British, and Canadian English'
author:
  - 'Ben Bullock <bkb@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-EN-ABC
no_index:
  directory:
    - t
    - inc
requires:
  JSON::Parse: 0.14
resources:
  bugtracker: https://github.com/benkasminbullock/Lingua-EN-ABC/issues
  repository: https://github.com/benkasminbullock/Lingua-EN-ABC
version: 0.01
